// Countries and Cities Data
const countriesCities = {
  "Afghanistan": ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"],
  "Albania": ["Tirana", "Durres", "Vlore", "Shkoder", "Elbasan"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  "Andorra": ["Andorra la Vella", "Escaldes-Engordany", "Encamp"],
  "Angola": ["Luanda", "Huambo", "Lobito", "Benguela"],
  "Argentina": ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata"],
  "Armenia": ["Yerevan", "Gyumri", "Vanadzor"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra"],
  "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit"],
  "Bahrain": ["Manama", "Riffa", "Muharraq"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liege"],
  "Brazil": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas"],
  "Canada": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton"],
  "Chile": ["Santiago", "Valparaiso", "Concepcion", "La Serena"],
  "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Xi'an"],
  "Colombia": ["Bogota", "Medellin", "Cali", "Barranquilla"],
  "Costa Rica": ["San Jose", "Cartago", "Heredia", "Alajuela"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek"],
  "Cuba": ["Havana", "Santiago de Cuba", "Camaguey", "Holguin"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  "Dominican Republic": ["Santo Domingo", "Santiago", "La Romana"],
  "Ecuador": ["Quito", "Guayaquil", "Cuenca"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said"],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel"],
  "Estonia": ["Tallinn", "Tartu", "Narva"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekelle"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa"],
  "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes"],
  "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Takoradi"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion"],
  "Guatemala": ["Guatemala City", "Quetzaltenango", "Escuintla"],
  "Honduras": ["Tegucigalpa", "San Pedro Sula", "La Ceiba"],
  "Hong Kong": ["Hong Kong", "Kowloon"],
  "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc"],
  "Iceland": ["Reykjavik", "Kopavogur", "Hafnarfjordur"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan"],
  "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz"],
  "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil"],
  "Ireland": ["Dublin", "Cork", "Limerick", "Galway"],
  "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa"],
  "Jamaica": ["Kingston", "Montego Bay", "Spanish Town"],
  "Japan": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka"],
  "Jordan": ["Amman", "Zarqa", "Irbid", "Russeifa"],
  "Kazakhstan": ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru"],
  "Kuwait": ["Kuwait City", "Al Ahmadi", "Hawalli"],
  "Latvia": ["Riga", "Daugavpils", "Liepaja"],
  "Lebanon": ["Beirut", "Tripoli", "Sidon"],
  "Libya": ["Tripoli", "Benghazi", "Misrata"],
  "Lithuania": ["Vilnius", "Kaunas", "Klaipeda"],
  "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette"],
  "Malaysia": ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh"],
  "Maldives": ["Male"],
  "Malta": ["Valletta", "Birkirkara", "Sliema"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
  "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan"],
  "Morocco": ["Casablanca", "Rabat", "Fez", "Marrakesh", "Tangier"],
  "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton"],
  "Nigeria": ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  "Oman": ["Muscat", "Seeb", "Salalah", "Bawshar"],
  "Pakistan": ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad", "Gujranwala", "Sialkot", "Multan", "Peshawar", "Quetta"],
  "Panama": ["Panama City", "Colon", "David"],
  "Paraguay": ["Asuncion", "Ciudad del Este", "San Lorenzo"],
  "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo"],
  "Philippines": ["Manila", "Quezon City", "Davao City", "Cebu City", "Zamboanga City"],
  "Poland": ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan"],
  "Portugal": ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora"],
  "Qatar": ["Doha", "Al Rayyan", "Umm Salal"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  "Serbia": ["Belgrade", "Novi Sad", "Nis", "Kragujevac"],
  "Singapore": ["Singapore"],
  "Slovakia": ["Bratislava", "Kosice", "Presov"],
  "Slovenia": ["Ljubljana", "Maribor", "Celje"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga"],
  "Sri Lanka": ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa", "Negombo"],
  "Sudan": ["Khartoum", "Omdurman", "Port Sudan"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
  "Syria": ["Damascus", "Aleppo", "Homs", "Latakia"],
  "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan"],
  "Tajikistan": ["Dushanbe", "Khujand", "Kulob"],
  "Tanzania": ["Dar es Salaam", "Mwanza", "Zanzibar City", "Arusha"],
  "Thailand": ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Phuket"],
  "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana"],
  "Turkmenistan": ["Ashgabat", "Turkmenabat", "Dasoguz"],
  "UAE": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
  "UK": ["London", "Birmingham", "Manchester", "Glasgow", "Leeds", "Liverpool", "Newcastle"],
  "USA": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"],
  "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv"],
  "Uruguay": ["Montevideo", "Salto", "Ciudad de la Costa"],
  "Uzbekistan": ["Tashkent", "Samarkand", "Namangan"],
  "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong"],
  "Yemen": ["Sana'a", "Aden", "Taiz"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza"]
};

const getAllCountries = () => Object.keys(countriesCities).sort();

const getCitiesByCountry = (country) => countriesCities[country] || [];

module.exports = { countriesCities, getAllCountries, getCitiesByCountry };
