const WorkSchedule = require("../models/WorkSchedule");
const User = require("../models/User");
const EODReport = require("../models/EODReport");
const EODFlag = require("../models/EODFlag");
const LeaveRequest = require("../models/LeaveRequest");
const TimeEntry = require("../models/TimeEntry");
const { createNotification } = require("../utils/notifications");
const { sendToUser, isOneSignalEnabled } = require("./oneSignal");

function parseHHMM(hhmm) {
  const m = String(hhmm || "").trim().match(/^(\d{1,2}):(\d{2})$/);
  if (!m) return null;
  const h = Number(m[1]);
  const min = Number(m[2]);
  if (!Number.isFinite(h) || !Number.isFinite(min) || h < 0 || h > 23 || min < 0 || min > 59) return null;
  return h * 60 + min;
}

function getNowPartsInTimeZone(timeZone) {
  const fmt = new Intl.DateTimeFormat("en-US", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });

  const parts = fmt.formatToParts(new Date());
  const get = (type) => parts.find((p) => p.type === type)?.value;

  const year = Number(get("year"));
  const month = Number(get("month"));
  const day = Number(get("day"));
  const hour = Number(get("hour"));
  const minute = Number(get("minute"));

  if (![year, month, day, hour, minute].every((x) => Number.isFinite(x))) return null;
  return { year, month, day, hour, minute };
}

function toDateRangeUTCForTZDay(tzParts) {
  // tzParts: year, month, day in that timezone.
  // We'll approximate range by constructing date in UTC using that Y-M-D and expanding 36h.
  // Used only for querying by date (not for exact boundary comparisons).
  const start = new Date(Date.UTC(tzParts.year, tzParts.month - 1, tzParts.day, 0, 0, 0, 0));
  const end = new Date(Date.UTC(tzParts.year, tzParts.month - 1, tzParts.day, 23, 59, 59, 999));
  return { start, end };
}

async function ensureMissingFlag({ userId, date }) {
  try {
    const existing = await EODFlag.findOne({ userId, date, status: "missing" }).lean();
    if (existing) return existing;
    return await EODFlag.create({ userId, date, status: "missing", severity: "high", autoGenerated: true });
  } catch {
    return null;
  }
}

async function hasEODReportForDay({ userId, start, end }) {
  const existing = await EODReport.findOne({ userId, date: { $gte: start, $lte: end } }).select("_id").lean();
  return Boolean(existing);
}

async function runEODTick() {
  const schedules = await WorkSchedule.find({ isActive: true }).lean();
  if (!Array.isArray(schedules) || schedules.length === 0) return;

  for (const s of schedules) {
    const tz = String(s.timezone || "America/New_York");
    const now = getNowPartsInTimeZone(tz);
    if (!now) continue;

    const nowMinutes = now.hour * 60 + now.minute;
    const shiftStartMins = parseHHMM(s.shiftStart);
    const shiftEndMins = parseHHMM(s.shiftEnd);
    if (shiftEndMins === null || shiftStartMins === null) continue;

    const userId = String(s.userId || "");
    if (!userId) continue;

    const user = await User.findById(userId).select("_id username name role").lean();
    if (!user) continue;

    const { start, end } = toDateRangeUTCForTZDay(now);

    // Check if user is on PTO/leave (exempt from EOD)
    const isOnLeave = await LeaveRequest.isUserOnLeave(userId, start);
    if (isOnLeave) {
      console.log(`[EOD] User ${userId} is on leave - skipping EOD check`);
      continue; // Skip all EOD processing for this user today
    }

    // Check for early clock-out (triggers immediate EOD requirement)
    const timeEntry = await TimeEntry.findOne({
      employee: user.username || user.name,
      date: { $gte: start, $lte: end },
    }).lean();

    let adjustedShiftEndMins = shiftEndMins;
    let isEarlyClockOut = false;
    let isOvertime = false;

    if (timeEntry?.clockOutAt) {
      const clockOutDate = new Date(timeEntry.clockOutAt);
      const clockOutMinutes = clockOutDate.getHours() * 60 + clockOutDate.getMinutes();
      
      // Early clock-out: left more than 30 min before shift end
      if (clockOutMinutes < shiftEndMins - 30) {
        isEarlyClockOut = true;
        adjustedShiftEndMins = clockOutMinutes; // Trigger EOD at actual clock-out
      }
      
      // Overtime: still clocked in past shift end + 30 min grace
      if (!timeEntry.clockOut && nowMinutes > shiftEndMins + 30) {
        isOvertime = true;
        // For overtime, use current time as trigger point (dynamic)
        adjustedShiftEndMins = nowMinutes - 10; // Reminder 10 min ago
      }
    }

    // No schedule exists - this is caught by WorkSchedule query, but handle edge case
    // Actually, if user has no schedule, they shouldn't be in this loop
    // The "block access" requirement is handled at clock-in time, not here

    const offset = Number(s.eodOffsetMinutes || -10);
    const reminderAt = (adjustedShiftEndMins + offset + 1440) % 1440;
    const closeAt = (adjustedShiftEndMins + 30 + 1440) % 1440;
    const escalateAt = (adjustedShiftEndMins + 60 + 1440) % 1440;

    // Reminder notification
    if (nowMinutes === reminderAt) {
      await createNotification({
        actor: "system",
        actorRole: "system",
        action: "EOD report due",
        resourceType: "EOD report",
        resourceName: `${now.year}-${String(now.month).padStart(2, "0")}-${String(now.day).padStart(2, "0")}`,
        assignees: [String(user._id), String(user.username || ""), String(user.name || "")].filter(Boolean),
        details: "End-of-Day Report due soon",
        resourceId: "",
      });
      
      // Push notification
      if (isOneSignalEnabled()) {
        await sendToUser(String(user._id), {
          heading: "EOD Report Due",
          content: "Your End-of-Day report is due soon. Please submit before the window closes.",
          data: { type: "eod_reminder", date: `${now.year}-${String(now.month).padStart(2, "0")}-${String(now.day).padStart(2, "0")}` },
          url: "/employee/clocked",
        });
      }
    }

    // Close window -> mark missing
    if (nowMinutes === closeAt) {
      const ok = await hasEODReportForDay({ userId: String(user._id), start, end });
      if (!ok) {
        await ensureMissingFlag({ userId: user._id, date: start });
        await createNotification({
          actor: "system",
          actorRole: "system",
          action: "missed",
          resourceType: "EOD report",
          resourceName: `${now.year}-${String(now.month).padStart(2, "0")}-${String(now.day).padStart(2, "0")}`,
          assignees: ["manager", "admin", "super-admin"],
          details: `${user.username || user.name || "User"} missed EOD report`,
          resourceId: "",
        });
        
        // Push notification to user
        if (isOneSignalEnabled()) {
          await sendToUser(String(user._id), {
            heading: "EOD Report Missing",
            content: "You missed submitting your End-of-Day report. Please submit ASAP to avoid escalation.",
            data: { type: "eod_missing", date: `${now.year}-${String(now.month).padStart(2, "0")}-${String(now.day).padStart(2, "0")}` },
            url: "/employee/clocked",
          });
        }
      }
    }

    // Escalation after 1 hour late
    if (nowMinutes === escalateAt) {
      const ok = await hasEODReportForDay({ userId: String(user._id), start, end });
      if (!ok) {
        await createNotification({
          actor: "system",
          actorRole: "system",
          action: "escalation",
          resourceType: "EOD report",
          resourceName: `${now.year}-${String(now.month).padStart(2, "0")}-${String(now.day).padStart(2, "0")}`,
          assignees: ["manager"],
          details: `${user.username || user.name || "User"} is 1 hour late on EOD report`,
          resourceId: "",
        });
        
        // Push notification to user
        if (isOneSignalEnabled()) {
          await sendToUser(String(user._id), {
            heading: "EOD Report Escalated",
            content: "Your missing EOD report has been escalated to management. Please submit immediately.",
            data: { type: "eod_escalation", date: `${now.year}-${String(now.month).padStart(2, "0")}-${String(now.day).padStart(2, "0")}` },
            url: "/employee/clocked",
          });
        }
      }
    }
  }
}

module.exports = {
  runEODTick,
  parseHHMM,
  getNowPartsInTimeZone,
};
