const mongoose = require("mongoose");

const EODFlagSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
    date: { type: Date, required: true, index: true },
    status: { type: String, enum: ["missing"], default: "missing", index: true },
    severity: { type: String, enum: ["high"], default: "high" },
    autoGenerated: { type: Boolean, default: true },
  },
  { timestamps: true }
);

EODFlagSchema.index({ userId: 1, date: -1, status: 1 }, { unique: true });

module.exports = mongoose.model("EODFlag", EODFlagSchema);
